# Generated by Django 5.2 on 2025-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experto',
            fields=[
                ('experto_cc', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(max_length=255)),
                ('clasificacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En Progreso'), ('completado', 'Completada')], max_length=20)),
            ],
            options={
                'db_table': 'experto',
                'managed': False,
            },
        ),
    ]
