# Generated by Django 5.2 on 2025-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('brigada_id', models.AutoField(primary_key=True, serialize=False)),
                ('investigacion_id', models.IntegerField()),
            ],
            options={
                'db_table': 'brigada',
                'get_latest_by': 'brigada_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrigadaExperto',
            fields=[
                ('brigada_experto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brigada_id', models.IntegerField()),
                ('experto_cc', models.IntegerField()),
            ],
            options={
                'db_table': 'brigada_experto',
                'managed': False,
            },
        ),
    ]
